import { INITIAL_COUNTRIES } from "@/config/countries";
import { INITIAL_CATEGORIES } from "@/config/categories";
import { classifyJobSponsorship } from "@/scoring/classifier";
import { generateCanonicalHash } from "@/normalization";

export const STATIC_SOURCES = [
  { id: "seed_direct", name: "SponsorAJobs Direct Feed", type: "feed", active: 1, terms_url: "https://sponsorajobs.com/terms", attribution_required: 0 },
  { id: "usajobs", name: "USAJobs Federal API", type: "api", active: 0, terms_url: "https://developer.usajobs.gov/API-Terms", attribution_required: 0 },
  { id: "adzuna", name: "Adzuna Job API", type: "api", active: 0, terms_url: "https://developer.adzuna.com/terms", attribution_required: 1 },
  { id: "ashby", name: "Ashby ATS Feeds", type: "ats", active: 0, terms_url: "https://www.ashbyhq.com/terms", attribution_required: 0 },
  { id: "workable", name: "Workable ATS Feeds", type: "ats", active: 0, terms_url: "https://www.workable.com/terms", attribution_required: 0 },
];

export const STATIC_COMPANIES = [
  { id: "comp_atlassian", name: "Atlassian", normalized_name: "atlassian", country_code: "AU", industry: "Technology", website: "https://atlassian.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_canva", name: "Canva", normalized_name: "canva", country_code: "AU", industry: "Technology", website: "https://canva.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_revolut", name: "Revolut", normalized_name: "revolut", country_code: "GB", industry: "Fintech", website: "https://revolut.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_monzo", name: "Monzo Bank", normalized_name: "monzo bank", country_code: "GB", industry: "Fintech", website: "https://monzo.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_nhs", name: "NHS England Trust", normalized_name: "nhs england trust", country_code: "GB", industry: "Healthcare", website: "https://nhs.uk", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_arup", name: "Arup Engineering", normalized_name: "arup engineering", country_code: "GB", industry: "Engineering", website: "https://arup.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_shopify", name: "Shopify", normalized_name: "shopify", country_code: "CA", industry: "E-Commerce", website: "https://shopify.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_xero", name: "Xero", normalized_name: "xero", country_code: "NZ", industry: "Technology", website: "https://xero.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_bhp", name: "BHP Mining", normalized_name: "bhp mining", country_code: "AU", industry: "Engineering", website: "https://bhp.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
  { id: "comp_datacom", name: "Datacom NZ", normalized_name: "datacom nz", country_code: "NZ", industry: "Technology", website: "https://datacom.com", logo_url: null, careers_url: null, description: null, sponsorship_signal: null, created_at: "2026-01-01T00:00:00.000Z", updated_at: "2026-01-01T00:00:00.000Z" },
];

export const STATIC_COUNTRIES = INITIAL_COUNTRIES.map((c) => ({
  id: `c_${c.code.toLowerCase()}`,
  code: c.code,
  name: c.name,
  slug: c.slug,
  flag: c.flag,
  currency: c.currency,
  active: 1,
  seo_title: c.seoTitle,
  seo_description: c.seoDescription,
  created_at: "2026-01-01T00:00:00.000Z",
  updated_at: "2026-01-01T00:00:00.000Z",
}));

export const STATIC_CATEGORIES = INITIAL_CATEGORIES.map((c) => ({
  id: c.id,
  name: c.name,
  slug: c.slug,
  parent_id: c.parentId || null,
  active: 1,
  seo_title: c.seoTitle || null,
  seo_description: c.seoDescription || null,
  created_at: "2026-01-01T00:00:00.000Z",
  updated_at: "2026-01-01T00:00:00.000Z",
}));

export const STATIC_JOBS_RAW = [
  // UK
  {
    title: "Senior Civil Structural Engineer",
    companyId: "comp_arup",
    categorySlug: "engineering",
    city: "London",
    region: "Greater London",
    country: "GB",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 65000,
    salaryMax: 85000,
    currency: "GBP",
    desc: "Arup is looking for a Senior Civil Structural Engineer in London. We offer full UK Skilled Worker visa sponsorship and Certificate of Sponsorship (CoS) for international candidates.",
    source: "seed_direct",
  },
  {
    title: "Staff Backend Engineer (Fintech)",
    companyId: "comp_revolut",
    categorySlug: "information-technology",
    city: "London",
    region: "Greater London",
    country: "GB",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 110000,
    salaryMax: 145000,
    currency: "GBP",
    desc: "Join Revolut as Staff Backend Engineer. Visa sponsorship is available for eligible senior software engineering candidates.",
    source: "seed_direct",
  },
  {
    title: "Registered Nurse - Acute Care",
    companyId: "comp_nhs",
    categorySlug: "healthcare",
    city: "Birmingham",
    region: "West Midlands",
    country: "GB",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 34000,
    salaryMax: 42000,
    currency: "GBP",
    desc: "NHS Trust invites applications for Registered Nurses. UK Health and Care Worker visa sponsorship provided along with OSCE support.",
    source: "seed_direct",
  },
  {
    title: "Junior Data Analyst",
    companyId: "comp_monzo",
    categorySlug: "information-technology",
    city: "London",
    region: "Greater London",
    country: "GB",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 45000,
    salaryMax: 55000,
    currency: "GBP",
    desc: "Entry-to-mid level Data Analyst role. Note: candidates must have unrestricted work authorization to apply; sponsorship is not available.",
    source: "seed_direct",
  },
  {
    title: "Project Delivery Manager - Construction",
    companyId: "comp_arup",
    categorySlug: "construction",
    city: "Manchester",
    region: "Greater Manchester",
    country: "GB",
    remoteType: "ONSITE",
    employmentType: "CONTRACT",
    salaryMin: 55000,
    salaryMax: 70000,
    currency: "GBP",
    desc: "Lead infrastructure project deliveries. Visa support may be available for exceptional project managers with specialized major rail experience.",
    source: "seed_direct",
  },
  {
    title: "Lead Site Reliability Engineer",
    companyId: "comp_monzo",
    categorySlug: "information-technology",
    city: "London",
    region: "Greater London",
    country: "GB",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 120000,
    salaryMax: 160000,
    currency: "GBP",
    desc: "Architect scalable infrastructure for Monzo. Skilled Worker visa sponsorship available.",
    source: "seed_direct",
  },

  // US
  {
    title: "Principal Distributed Systems Architect",
    companyId: "comp_atlassian",
    categorySlug: "information-technology",
    city: "San Francisco",
    region: "California",
    country: "US",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 210000,
    salaryMax: 270000,
    currency: "USD",
    desc: "Lead core distributed systems. We offer H-1B transfer and Green Card sponsorship for senior and principal tier engineers.",
    source: "seed_direct",
  },
  {
    title: "Geotechnical Mining Engineer",
    companyId: "comp_bhp",
    categorySlug: "engineering",
    city: "Austin",
    region: "Texas",
    country: "US",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 130000,
    salaryMax: 175000,
    currency: "USD",
    desc: "BHP is expanding US mining operations. Employment sponsorship and O-1/H-1B visa support provided for specialized geological candidates.",
    source: "seed_direct",
  },
  {
    title: "Financial Planning & Analysis Manager",
    companyId: "comp_shopify",
    categorySlug: "finance",
    city: "New York",
    region: "New York",
    country: "US",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 140000,
    salaryMax: 180000,
    currency: "USD",
    desc: "Manage group-wide financial forecasts. Candidates must already have the right to work in the US without employer sponsorship.",
    source: "seed_direct",
  },
  {
    title: "Full Stack Product Engineer",
    companyId: "comp_canva",
    categorySlug: "information-technology",
    city: "Seattle",
    region: "Washington",
    country: "US",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 160000,
    salaryMax: 205000,
    currency: "USD",
    desc: "Build next-gen creative tools. H-1B sponsorship and work visa sponsorship offered for qualified candidates.",
    source: "seed_direct",
  },
  {
    title: "Healthcare Compliance Specialist",
    companyId: "comp_nhs",
    categorySlug: "healthcare",
    city: "Boston",
    region: "Massachusetts",
    country: "US",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 95000,
    salaryMax: 120000,
    currency: "USD",
    desc: "US citizenship or Green Card required exclusively for federal compliance clearances.",
    source: "seed_direct",
  },
  {
    title: "Machine Learning Research Scientist",
    companyId: "comp_canva",
    categorySlug: "information-technology",
    city: "San Francisco",
    region: "California",
    country: "US",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 220000,
    salaryMax: 310000,
    currency: "USD",
    desc: "Generative AI research. Visa sponsorship is available and relocation package included.",
    source: "seed_direct",
  },

  // Australia
  {
    title: "Senior Full Stack Engineer (React/Node)",
    companyId: "comp_atlassian",
    categorySlug: "information-technology",
    city: "Sydney",
    region: "New South Wales",
    country: "AU",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 160000,
    salaryMax: 210000,
    currency: "AUD",
    desc: "Join Atlassian in Sydney. We sponsor international talent on TSS Subclass 482 and Skills in Demand visas.",
    source: "seed_direct",
  },
  {
    title: "Civil Highway Design Engineer",
    companyId: "comp_arup",
    categorySlug: "engineering",
    city: "Melbourne",
    region: "Victoria",
    country: "AU",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 125000,
    salaryMax: 155000,
    currency: "AUD",
    desc: "Design major arterial highways. Employer sponsored position via subclass 482 visa with pathway to subclass 186 permanent residency.",
    source: "seed_direct",
  },
  {
    title: "Senior Product Designer",
    companyId: "comp_canva",
    categorySlug: "information-technology",
    city: "Sydney",
    region: "New South Wales",
    country: "AU",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 150000,
    salaryMax: 195000,
    currency: "AUD",
    desc: "Lead Canva design systems. Relocation and work visa sponsorship provided for international applicants.",
    source: "seed_direct",
  },
  {
    title: "Principal Mining Mechanical Engineer",
    companyId: "comp_bhp",
    categorySlug: "engineering",
    city: "Perth",
    region: "Western Australia",
    country: "AU",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 180000,
    salaryMax: 240000,
    currency: "AUD",
    desc: "Oversee heavy machinery assets. Subclass 482 employer sponsorship available for experienced mining engineers.",
    source: "seed_direct",
  },
  {
    title: "Clinical Nurse Specialist - Oncology",
    companyId: "comp_nhs",
    categorySlug: "healthcare",
    city: "Brisbane",
    region: "Queensland",
    country: "AU",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 98000,
    salaryMax: 120000,
    currency: "AUD",
    desc: "State healthcare system hiring international oncology nurses. Employer sponsorship provided via subclass 482 / 186.",
    source: "seed_direct",
  },
  {
    title: "Commercial Construction Project Manager",
    companyId: "comp_arup",
    categorySlug: "construction",
    city: "Adelaide",
    region: "South Australia",
    country: "AU",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 140000,
    salaryMax: 175000,
    currency: "AUD",
    desc: "Deliver landmark commercial projects in Adelaide. Visa sponsorship available for chartered project managers.",
    source: "seed_direct",
  },

  // Canada
  {
    title: "Staff Cloud Platform Architect",
    companyId: "comp_shopify",
    categorySlug: "information-technology",
    city: "Toronto",
    region: "Ontario",
    country: "CA",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 180000,
    salaryMax: 240000,
    currency: "CAD",
    desc: "Architect Shopify's global commerce engine. This position has positive LMIA support and work permit sponsorship for eligible international candidates.",
    source: "seed_direct",
  },
  {
    title: "Senior Geotechnical Structural Engineer",
    companyId: "comp_arup",
    categorySlug: "engineering",
    city: "Vancouver",
    region: "British Columbia",
    country: "CA",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 120000,
    salaryMax: 160000,
    currency: "CAD",
    desc: "Seismic and structural geotechnical modeling. LMIA supported work visa available for licensed P.Eng / internationally qualified candidates.",
    source: "seed_direct",
  },
  {
    title: "Senior Risk & Compliance Analyst",
    companyId: "comp_revolut",
    categorySlug: "finance",
    city: "Montreal",
    region: "Quebec",
    country: "CA",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 90000,
    salaryMax: 120000,
    currency: "CAD",
    desc: "Manage Canadian regulatory reporting. Candidates must have unrestricted work authorization; no sponsorship provided.",
    source: "seed_direct",
  },
  {
    title: "Senior Frontend Engineer (Design Systems)",
    companyId: "comp_shopify",
    categorySlug: "information-technology",
    city: "Ottawa",
    region: "Ontario",
    country: "CA",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 155000,
    salaryMax: 200000,
    currency: "CAD",
    desc: "Build Polaris design components. Employer sponsorship and Canadian work permit support offered.",
    source: "seed_direct",
  },
  {
    title: "Supply Chain Operations Lead",
    companyId: "comp_shopify",
    categorySlug: "logistics",
    city: "Calgary",
    region: "Alberta",
    country: "CA",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 95000,
    salaryMax: 130000,
    currency: "CAD",
    desc: "Oversee Canadian fulfillment network logistics. Temporary foreign worker LMIA support may be considered.",
    source: "seed_direct",
  },
  {
    title: "Cybersecurity Threat Hunter",
    companyId: "comp_shopify",
    categorySlug: "information-technology",
    city: "Toronto",
    region: "Ontario",
    country: "CA",
    remoteType: "REMOTE",
    employmentType: "FULL_TIME",
    salaryMin: 140000,
    salaryMax: 190000,
    currency: "CAD",
    desc: "Detect complex intrusions. Work visa sponsorship provided for senior security analysts.",
    source: "seed_direct",
  },

  // New Zealand
  {
    title: "Principal Software Architect",
    companyId: "comp_xero",
    categorySlug: "information-technology",
    city: "Wellington",
    region: "Wellington",
    country: "NZ",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 165000,
    salaryMax: 215000,
    currency: "NZD",
    desc: "Xero is an Accredited Employer. We provide full Accredited Employer Work Visa (AEWV) and Green List fast-track residency sponsorship.",
    source: "seed_direct",
  },
  {
    title: "Senior Cloud Infrastructure Engineer",
    companyId: "comp_datacom",
    categorySlug: "information-technology",
    city: "Auckland",
    region: "Auckland",
    country: "NZ",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 140000,
    salaryMax: 180000,
    currency: "NZD",
    desc: "Enterprise cloud migrations on AWS/Azure. AEWV accredited employer sponsorship provided.",
    source: "seed_direct",
  },
  {
    title: "Structural Seismic Engineer",
    companyId: "comp_arup",
    categorySlug: "engineering",
    city: "Christchurch",
    region: "Canterbury",
    country: "NZ",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 120000,
    salaryMax: 155000,
    currency: "NZD",
    desc: "Earthquake engineering & structural assessment. Accredited employer work visa sponsorship available on Green List Tier 1.",
    source: "seed_direct",
  },
  {
    title: "Registered Midwife / Neonatal Nurse",
    companyId: "comp_nhs",
    categorySlug: "healthcare",
    city: "Auckland",
    region: "Auckland",
    country: "NZ",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 85000,
    salaryMax: 110000,
    currency: "NZD",
    desc: "Health NZ accredited employer sponsorship and Green List Straight to Residence pathway for registered nurses.",
    source: "seed_direct",
  },
  {
    title: "Senior Commercial Solicitor",
    companyId: "comp_xero",
    categorySlug: "finance",
    city: "Auckland",
    region: "Auckland",
    country: "NZ",
    remoteType: "HYBRID",
    employmentType: "FULL_TIME",
    salaryMin: 130000,
    salaryMax: 170000,
    currency: "NZD",
    desc: "Lead SaaS enterprise contracts. Note: candidates must hold a current NZ practicing certificate and unrestricted right to work.",
    source: "seed_direct",
  },
  {
    title: "Civil Project Surveyor",
    companyId: "comp_arup",
    categorySlug: "construction",
    city: "Hamilton",
    region: "Waikato",
    country: "NZ",
    remoteType: "ONSITE",
    employmentType: "FULL_TIME",
    salaryMin: 95000,
    salaryMax: 125000,
    currency: "NZD",
    desc: "Geodetic and cadastral surveying for major highway projects. Visa sponsorship available for registered surveyors.",
    source: "seed_direct",
  }
];

export const STATIC_JOBS = STATIC_JOBS_RAW.map((raw, i) => {
  const jobId = `job_seed_${i + 1}`;
  const comp = STATIC_COMPANIES.find((c) => c.id === raw.companyId);
  const companyName = comp ? comp.name : "Employer";
  const applyUrl = `https://careers.example.com/apply/${jobId}?source=sponsorajobs`;
  const jobUrl = `https://sponsorajobs.com/job/${jobId}`;
  const hash = generateCanonicalHash(companyName, raw.title, `${raw.city}, ${raw.country}`, applyUrl);
  const classification = classifyJobSponsorship(raw.desc, raw.country);
  const categoryId = `cat_${raw.categorySlug === 'engineering' ? 'eng' : raw.categorySlug === 'healthcare' ? 'health' : raw.categorySlug === 'construction' ? 'const' : raw.categorySlug === 'finance' ? 'fin' : raw.categorySlug === 'logistics' ? 'logistics' : 'tech'}`;
  const category = STATIC_CATEGORIES.find((c) => c.id === categoryId);

  return {
    id: jobId,
    source_id: raw.source,
    source_job_id: `src_${i + 1}`,
    canonical_hash: hash,
    title: raw.title,
    company_id: raw.companyId,
    company_name: companyName,
    company_logo: comp?.logo_url || null,
    company_industry: comp?.industry || null,
    company_website: comp?.website || null,
    category_id: categoryId,
    category_name: category?.name || raw.categorySlug,
    category_slug: raw.categorySlug,
    description: raw.desc,
    description_clean: raw.desc,
    location: `${raw.city}, ${raw.country}`,
    city: raw.city,
    region: raw.region,
    country_code: raw.country,
    remote_type: raw.remoteType,
    employment_type: raw.employmentType,
    salary_min: raw.salaryMin,
    salary_max: raw.salaryMax,
    salary_currency: raw.currency,
    job_url: jobUrl,
    apply_url: applyUrl,
    source_url: applyUrl,
    published_at: new Date(Date.now() - i * 86400000 * 0.7).toISOString(),
    first_seen_at: new Date(Date.now() - i * 86400000 * 0.7).toISOString(),
    last_seen_at: new Date().toISOString(),
    sponsorship_score: classification.score,
    sponsorship_label: classification.label,
    sponsorship_positive_evidence: JSON.stringify(classification.positiveEvidence),
    sponsorship_negative_evidence: JSON.stringify(classification.negativeEvidence),
    visa_keywords: JSON.stringify(classification.keywords),
    quality_score: 100,
    status: "active",
    is_featured: i % 5 === 0 ? 1 : 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
});
